name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all
    - uses: ./
      id: upload_test
      env:
        S3_ACL: 'public-read'
      with:
        store_name: 's3'
        source_dir: 'src/stores'
        s3_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        s3_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        s3_region: ${{ secrets.AWS_REGION }}
        s3_bucket_name: ${{ secrets.AWS_UPLOAD_BUCKET }}
        s3_acl: |
          function generateInputValue() {
            console.log(env.S3_ACL);
            core.info('Log from custom input value generator function');
            return env.S3_ACL; // process.env is available as env
          }
        s3_path: |
          function generateInputValue() {
            const date = new Date().toISOString().split('T');
            const ymd = date[0];
            const hms = date[1].split('.')[0].replace(/:/g, '_');
            console.log(`Date Split: ${ymd}, ${hms}`);
            return `payment-svc/dev/${ymd}/${hms}`
          }
    - name: Test output
      run: |
        echo Base Url: ${{ steps.upload_test.outputs.s3BaseUrl }}
        echo Upload Count: ${{ steps.upload_test.outputs.uploadCount }}